#Reading material:
#HELP: https://cloud.google.com/build/docs/deploy-containerized-application-cloud-run
#HELP: https://cloud.google.com/build/docs/automate-builds
#HELP: https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/danielvichi/danielvichi-production/portfolio:latest",
        "--build-arg=BUILD_PROD=1",
        ".",
      ]
  # Push the container image to Container Registry
  - id: docker-push
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/danielvichi/danielvichi-production/portfolio:latest",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "danielvichi-production",
        "--image",
        "us-west1-docker.pkg.dev/danielvichi/danielvichi-production/portfolio:latest",
        "--region",
        "us-west1",
        "--port=3000",
        "--allow-unauthenticated",
        "--set-secrets=NEXT_GTM_ID=GTM-PH3MDZM7",
      ]
timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
